version: "3.8"
services:
  mongo:
    container_name: 'core-db'
    image: mongo:latest
    ports:
      - 27017:27017

  myapp:
    container_name: 'core-service'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo
